BUCKET_NAME = 'fettay'
BENIGN_LIST = 'data/benign.csv'
MALICIOUS_LIST = 'data/malicious.csv'
MALICIOUS_DF = 'data/infomals.csv'
DATADIR = 'pdfs/'
DATAMALDIR ='pdfsmal/'
LOCAL_BUCKET = '/specific/mansour/raphaelf/data/'
BENIGN = 0
MALICIOUS = 1